project:
  type: website
  output-dir: "."

website:
  title: "Gannon Moore"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© YOUR NAME, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
---
title: "Habits"
author: YOUR_NAME
date: November 27, 2023
format: 
  html
---    
quarto render
```{r setup}
#| include: false
library(tidyverse)
library(skimr)  
library(ggthemes)  # additional ggplot themes
library(hrbrthemes)  # additional ggplot themes and more

